/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ClusterHealthResponse } from "./clusterHealthResponse";
import type { ErrorDetail } from "./errorDetail";

export interface ApiResponseClusterHealthResponse {
  success?: boolean;
  data?: ClusterHealthResponse;
  error?: ErrorDetail;
  message?: string;
  timestamp?: string;
}
