/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserDto } from "./userDto";
import type { ErrorDetail } from "./errorDetail";

export interface ApiResponseUserDto {
  success?: boolean;
  data?: UserDto;
  error?: ErrorDetail;
  message?: string;
  timestamp?: string;
}
