/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ClusterLogsResponse } from "./clusterLogsResponse";
import type { ErrorDetail } from "./errorDetail";

export interface ApiResponseClusterLogsResponse {
  success?: boolean;
  data?: ClusterLogsResponse;
  error?: ErrorDetail;
  message?: string;
  timestamp?: string;
}
