/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ClusterResponse } from "./clusterResponse";
import type { ErrorDetail } from "./errorDetail";

export interface ApiResponseClusterResponse {
  success?: boolean;
  data?: ClusterResponse;
  error?: ErrorDetail;
  message?: string;
  timestamp?: string;
}
