/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ClusterConnectionDTO } from "./clusterConnectionDTO";
import type { ErrorDetail } from "./errorDetail";

export interface ApiResponseClusterConnectionDTO {
  success?: boolean;
  data?: ClusterConnectionDTO;
  error?: ErrorDetail;
  message?: string;
  timestamp?: string;
}
