/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseVoidData } from "./apiResponseVoidData";
import type { ErrorDetail } from "./errorDetail";

export interface ApiResponseVoid {
  success?: boolean;
  data?: ApiResponseVoidData;
  error?: ErrorDetail;
  message?: string;
  timestamp?: string;
}
