/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { NodeStatsResponse } from "./nodeStatsResponse";
import type { ErrorDetail } from "./errorDetail";

export interface ApiResponseListNodeStatsResponse {
  success?: boolean;
  data?: NodeStatsResponse[];
  error?: ErrorDetail;
  message?: string;
  timestamp?: string;
}
