/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseMapStringObjectData } from "./apiResponseMapStringObjectData";
import type { ErrorDetail } from "./errorDetail";

export interface ApiResponseMapStringObject {
  success?: boolean;
  data?: ApiResponseMapStringObjectData;
  error?: ErrorDetail;
  message?: string;
  timestamp?: string;
}
