/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseObjectData } from "./apiResponseObjectData";
import type { ErrorDetail } from "./errorDetail";

export interface ApiResponseObject {
  success?: boolean;
  data?: ApiResponseObjectData;
  error?: ErrorDetail;
  message?: string;
  timestamp?: string;
}
