/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BackupInfo } from "./backupInfo";
import type { ErrorDetail } from "./errorDetail";

export interface ApiResponseListBackupInfo {
  success?: boolean;
  data?: BackupInfo[];
  error?: ErrorDetail;
  message?: string;
  timestamp?: string;
}
