/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Cluster } from "./cluster";
import type { ErrorDetail } from "./errorDetail";

export interface ApiResponseCluster {
  success?: boolean;
  data?: Cluster;
  error?: ErrorDetail;
  message?: string;
  timestamp?: string;
}
