/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ClusterMetricsResponse } from "./clusterMetricsResponse";
import type { ErrorDetail } from "./errorDetail";

export interface ApiResponseClusterMetricsResponse {
  success?: boolean;
  data?: ClusterMetricsResponse;
  error?: ErrorDetail;
  message?: string;
  timestamp?: string;
}
