/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RestoreResponse } from "./restoreResponse";
import type { ErrorDetail } from "./errorDetail";

export interface ApiResponseRestoreResponse {
  success?: boolean;
  data?: RestoreResponse;
  error?: ErrorDetail;
  message?: string;
  timestamp?: string;
}
