/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AuthResponse } from "./authResponse";
import type { ErrorDetail } from "./errorDetail";

export interface ApiResponseAuthResponse {
  success?: boolean;
  data?: AuthResponse;
  error?: ErrorDetail;
  message?: string;
  timestamp?: string;
}
