/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { NodeLogsResponse } from "./nodeLogsResponse";
import type { ErrorDetail } from "./errorDetail";

export interface ApiResponseNodeLogsResponse {
  success?: boolean;
  data?: NodeLogsResponse;
  error?: ErrorDetail;
  message?: string;
  timestamp?: string;
}
