/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DashboardSummaryResponse } from "./dashboardSummaryResponse";
import type { ErrorDetail } from "./errorDetail";

export interface ApiResponseDashboardSummaryResponse {
  success?: boolean;
  data?: DashboardSummaryResponse;
  error?: ErrorDetail;
  message?: string;
  timestamp?: string;
}
