/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Backup } from "./backup";
import type { ErrorDetail } from "./errorDetail";

export interface ApiResponseListBackup {
  success?: boolean;
  data?: Backup[];
  error?: ErrorDetail;
  message?: string;
  timestamp?: string;
}
