/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Task } from "./task";
import type { ErrorDetail } from "./errorDetail";

export interface ApiResponseListTask {
  success?: boolean;
  data?: Task[];
  error?: ErrorDetail;
  message?: string;
  timestamp?: string;
}
