/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AuthResponse {
  token?: string;
  type?: string;
  expiresIn?: number;
  username?: string;
  role?: string;
}
