/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type BackupInfoStatus =
  (typeof BackupInfoStatus)[keyof typeof BackupInfoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BackupInfoStatus = {
  PENDING: "PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
} as const;
