/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BackupInfoStatus } from "./backupInfoStatus";

export interface BackupInfo {
  id?: string;
  clusterId?: string;
  name?: string;
  status?: BackupInfoStatus;
  sizeBytes?: number;
  createdAt?: string;
  completedAt?: string;
}
