/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BackupStatus } from "./backupStatus";

export interface Backup {
  id?: string;
  clusterId?: string;
  name?: string;
  status?: BackupStatus;
  sizeBytes?: number;
  storagePath?: string;
  backupType?: string;
  createdAt?: string;
  completedAt?: string;
  errorMessage?: string;
}
