/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ChangePasswordRequest {
  currentPassword: string;
  /**
   * @minLength 6
   * @maxLength 2147483647
   */
  newPassword: string;
  confirmPassword: string;
}
