/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ClusterConnectionDTO {
  clusterId?: string;
  clusterName?: string;
  host?: string;
  port?: number;
  username?: string;
  password?: string;
  rootPassword?: string;
  connectionString?: string;
  proxyContainerName?: string;
  dockerNetwork?: string;
}
