/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ClusterStatus = (typeof ClusterStatus)[keyof typeof ClusterStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClusterStatus = {
  PROVISIONING: "PROVISIONING",
  HEALTHY: "HEALTHY",
  RUNNING: "RUNNING",
  DEGRADED: "DEGRADED",
  STOPPED: "STOPPED",
  DELETING: "DELETING",
  FAILED: "FAILED",
} as const;
