/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ClusterHealthResponseStatus } from "./clusterHealthResponseStatus";

export interface ClusterHealthResponse {
  clusterId?: string;
  status?: ClusterHealthResponseStatus;
  healthy?: boolean;
}
