/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { NodeLogsResponse } from "./nodeLogsResponse";

export interface ClusterLogsResponse {
  clusterId?: string;
  nodes?: NodeLogsResponse[];
}
