/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ClusterResponseStatus } from "./clusterResponseStatus";

export interface ClusterResponse {
  id?: string;
  name?: string;
  description?: string;
  mysqlVersion?: string;
  replicaCount?: number;
  status?: ClusterResponseStatus;
  dbUser?: string;
  proxyPort?: number;
  enableOrchestrator?: boolean;
  enableBackup?: boolean;
  totalNodes?: number;
  runningNodes?: number;
  errorMessage?: string;
  createdAt?: string;
  updatedAt?: string;
}
