/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ClusterStatus } from "./clusterStatus";

export interface Cluster {
  id?: string;
  name?: string;
  userId?: string;
  mysqlVersion?: string;
  replicaCount?: number;
  status?: ClusterStatus;
  networkId?: string;
  masterContainerId?: string;
  proxySqlContainerId?: string;
  replicaContainerIds?: string[];
  errorMessage?: string;
  description?: string;
  enableOrchestrator?: boolean;
  enableBackup?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
