/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ClusterResponseStatus =
  (typeof ClusterResponseStatus)[keyof typeof ClusterResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClusterResponseStatus = {
  PROVISIONING: "PROVISIONING",
  HEALTHY: "HEALTHY",
  RUNNING: "RUNNING",
  DEGRADED: "DEGRADED",
  STOPPED: "STOPPED",
  DELETING: "DELETING",
  SCALING: "SCALING",
  FAILED: "FAILED",
} as const;
