/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ClusterSummary {
  clusterId?: string;
  name?: string;
  status?: string;
  nodeCount?: number;
  healthyNodeCount?: number;
}
