/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ResourceConfig } from "./resourceConfig";
import type { NodeConfig } from "./nodeConfig";
import type { FeatureConfig } from "./featureConfig";

export interface CreateClusterRequest {
  /**
   * @minLength 3
   * @maxLength 50
   * @pattern ^[a-zA-Z][a-zA-Z0-9-_]*$
   */
  name: string;
  /** @pattern ^[58]\.[0-9]$ */
  mysqlVersion?: string;
  /**
   * @minimum 0
   * @maximum 5
   */
  replicaCount?: number;
  /**
   * @minLength 0
   * @maxLength 500
   */
  description?: string;
  resources?: ResourceConfig;
  masterConfig?: NodeConfig;
  replicaConfigs?: NodeConfig[];
  features?: FeatureConfig;
  masterNodeConfig?: NodeConfig;
}
