/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ResourceUsage } from "./resourceUsage";
import type { ClusterSummary } from "./clusterSummary";

export interface DashboardSummaryResponse {
  timestamp?: string;
  totalClusters?: number;
  runningClusters?: number;
  stoppedClusters?: number;
  failedClusters?: number;
  totalNodes?: number;
  healthyNodes?: number;
  unhealthyNodes?: number;
  resourceUsage?: ResourceUsage;
  clusters?: ClusterSummary[];
}
