/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetNodeLogsParams = {
  /**
   * Number of log lines to retrieve
   */
  lines?: number;
  /**
   * Include timestamps in log output
   */
  timestamps?: boolean;
};
