/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ListClustersParams = {
  /**
   * Page number (0-based)
   */
  page?: number;
  /**
   * Page size
   */
  size?: number;
  /**
   * Sort field
   */
  sortBy?: string;
  /**
   * Sort direction
   */
  sortDir?: string;
  /**
   * Enable pagination
   */
  paged?: boolean;
};
