/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { NodeRole } from "./nodeRole";
import type { NodeStatus } from "./nodeStatus";

export interface Node {
  id?: string;
  clusterId?: string;
  containerName?: string;
  role?: NodeRole;
  ipAddress?: string;
  port?: number;
  status?: NodeStatus;
  containerId?: string;
  cpuCores?: number;
  memory?: string;
  storage?: string;
  readOnly?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
