/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface NodeLogsResponse {
  nodeId?: string;
  containerName?: string;
  logs?: string;
  lineCount?: number;
  timestamp?: string;
}
