/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RegisterRequest {
  /**
   * @minLength 3
   * @maxLength 50
   * @pattern ^[a-zA-Z][a-zA-Z0-9_]*$
   */
  username: string;
  /**
   * @minLength 8
   * @maxLength 100
   * @pattern ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+$
   */
  password: string;
  email?: string;
}
