/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ResourceConfig {
  /**
   * @minimum 1
   * @maximum 16
   */
  cpuCores?: number;
  /** @pattern ^[1-9][0-9]*[GMK]$ */
  memory?: string;
}
