/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ResourceUsage {
  avgCpuPercent?: number;
  totalMemoryUsage?: number;
  totalMemoryLimit?: number;
  avgMemoryPercent?: number;
  totalNetworkRx?: number;
  totalNetworkTx?: number;
}
