/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ResourceUpdateConfig } from "./resourceUpdateConfig";

export interface ScaleRequest {
  /**
   * @minimum 0
   * @maximum 5
   */
  replicaCount: number;
  resources?: ResourceUpdateConfig;
}
