/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskType } from "./taskType";
import type { TaskStatus } from "./taskStatus";

export interface Task {
  id?: string;
  clusterId?: string;
  type?: TaskType;
  status?: TaskStatus;
  logOutput?: string;
  startedAt?: string;
  completedAt?: string;
  createdAt?: string;
}
