/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type TaskType = (typeof TaskType)[keyof typeof TaskType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskType = {
  DEPLOY: "DEPLOY",
  SCALE: "SCALE",
  RESTART: "RESTART",
  DELETE: "DELETE",
  FAILOVER: "FAILOVER",
} as const;
