/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UpdateProfileRequest {
  email?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  displayName?: string;
}
