/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserDtoRole } from "./userDtoRole";

export interface UserDto {
  id?: string;
  username?: string;
  email?: string;
  role?: UserDtoRole;
  enabled?: boolean;
  createdAt?: string;
  updatedAt?: string;
  clusterCount?: number;
}
